version: "3.8"

services:
    database:
        container_name: schema-first-poc
        image: postgres:12.8
        ports:
            - "${DB_PORT}:${DB_PORT}"
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_DB=${DB_NAME}
        healthcheck:
            test: "exit 0"
    migration:
        container_name: rep-migrations
        depends_on:
            database:
                condition: service_healthy
        image: liquibase/liquibase:4.17.0
        volumes:
            - ./src/database/migrations:/liquibase/changelog
        command:
            'update --username=${DB_USERNAME} --password=${DB_PASSWORD} --url=${DB_DOCKER_URL} --liquibase-schema-name=public
            --changelogFile="./master.json"'
